apiVersion: apps/v1
kind: Deployment
metadata:
  name: secure-password-api
  labels:
    app: secure-password-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: secure-password-api
  template:
    metadata:
      labels:
        app: secure-password-api
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/metrics"
        prometheus.io/port: "8000"
    spec:
      containers:
      - name: secure-password-api
        image: pselmani/personal:latest
        ports:
        - containerPort: 8000
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 10
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /ready
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 10
