apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "secure-password-api.fullname" . }}
  annotations:
{{- if .Values.prometheus.enabled }}
    prometheus.io/scrape: "true"
    prometheus.io/path: "{{ .Values.prometheus.path }}"
    prometheus.io/port: "8000"
{{- end }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "secure-password-api.fullname" . }}
  template:
    metadata:
      labels:
        app: {{ include "secure-password-api.fullname" . }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8000
          env:
{{- with .Values.env }}
{{ toYaml . | indent 12 }}
{{- end }}
          livenessProbe:
            httpGet:
              path: {{ .Values.livenessProbe.path }}
              port: 8000
            initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
          readinessProbe:
            httpGet:
              path: {{ .Values.readinessProbe.path }}
              port: 8000
            initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.readinessProbe.periodSeconds }}
